# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'snakesenza.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
from pygame import mixer
from kbc import kbc
import pymysql
import pandas as pd
from tkinter import ttk
import tkinter as tk
from tkinter import *
import admin
from USER import Ui_costomer


class Ui_Dialog(object):

    def __init__(self):
        self.uname = None
        self.mydb = pymysql.connect(host="127.0.0.1", port=3306,
                                    user="root", passwd="", database="quiz game")
        self.c = self.mydb.cursor()

    def open_USER(self):  # method to create an instance of open account
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_costomer()
        self.ui.setupUi(self.window)
        self.window.show()

    def open_admin(self):  # method to create an instance of open account
        self.window = QtWidgets.QMainWindow()
        self.ui = admin.Ui_admin()
        self.ui.setupUi(self.window)
        self.window.show()

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(447, 528)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, 0, 451, 531))
        self.label.setStyleSheet(
            "background-image: url(:/newPrefix/h1.jpg);")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("h1.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.textEdit = QtWidgets.QTextEdit(Dialog)
        self.textEdit.setGeometry(QtCore.QRect(100, 40, 241, 61))
        font = QtGui.QFont()
        font.setFamily("Ravie")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.textEdit.setFont(font)
        self.textEdit.setStyleSheet("background-color: transparent;\n"
                                    "color: white;\n"
                                    "border-style: outset;\n"
                                    "border-width:2px;\n"
                                    "border-radius:10px;\n"
                                    "border-color:blue;\n"
                                    "font:bold 14px;\n"
                                    "")
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(170, 250, 111, 41))
        self.pushButton.setStyleSheet("\n"
                                      "\n"
                                      "QPushButton {\n"
                                      "background-color:#0080FF;\n"
                                      "color: white;\n"
                                      "border-style: outset;\n"
                                      "border-width:2px;\n"
                                      "border-radius:10px;\n"
                                      "border-color:black;\n"
                                      "font:bold 14px;\n"
                                      "padding:6px;\n"
                                      "min-width:10px;\n"
                                      "\n"
                                      "}\n"
                                      "QPushButton:hover {\n"
                                      "background-color: rgb(173,216,230);\n"
                                      "color: rgb(255, 255, 255);\n"
                                      "}\n"
                                      "QPushButton:pressed {\n"
                                      "\n"
                                      "color:     rgb(0,0,0);\n"
                                      "}\n"
                                      "")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(170, 330, 111, 41))
        self.pushButton_2.setStyleSheet("\n"
                                        "\n"
                                        "QPushButton {\n"
                                        "background-color:#0080FF;\n"
                                        "color: white;\n"
                                        "border-style: outset;\n"
                                        "border-width:2px;\n"
                                        "border-radius:10px;\n"
                                        "border-color:black;\n"
                                        "font:bold 14px;\n"
                                        "padding:6px;\n"
                                        "min-width:10px;\n"
                                        "\n"
                                        "}\n"
                                        "QPushButton:hover {\n"
                                        "background-color: rgb(173,216,230);\n"
                                        "color: rgb(255, 255, 255);\n"
                                        "}\n"
                                        "QPushButton:pressed {\n"
                                        "\n"
                                        "color:     rgb(0,0,0);\n"
                                        "}\n"
                                        "")
        self.pushButton_2.setObjectName("pushButton_2")

        self.textEdit_2 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_2.setGeometry(QtCore.QRect(110, 140, 221, 71))
        self.textEdit_2.setStyleSheet("background-color: transparent;\n"
                                      "color: white;\n"
                                      "border-style: outset;\n"
                                      "\n"
                                      "border-radius:10px;\n"
                                      "\n"
                                      "font:bold 14px;\n"
                                      "")
        self.textEdit_2.setReadOnly(True)
        self.textEdit_2.setObjectName("textEdit_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        self.Dialog = Dialog
        mixer.init()
       # mixer.music.load('voice.mp3')
       # mixer.music.play()  # prantheis ma -1 for repeated saying

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Quiz Game"))
        self.textEdit.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                         "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                         "p, li { white-space: pre-wrap; }\n"
                                         "</style></head><body style=\" font-family:\'Ravie\'; font-size:14px; font-weight:600; font-style:normal;\">\n"
                                         "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:26pt; color:#FCFCFF;\">Quiz Game !</span></p></body></html>"))
        self.pushButton.setText(_translate("Dialog", "Admin Portal"))
        self.pushButton_2.setText(_translate("Dialog", "User Portal"))

        self.textEdit_2.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                           "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                           "p, li { white-space: pre-wrap; }\n"
                                           "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:14px; font-weight:600; font-style:normal;\">\n"
                                           "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:20pt; color:#FCFCFF;\">Portal Mode</span></p></body></html>"))
        self.pushButton.clicked.connect(self.func_admin)
        self.pushButton_2.clicked.connect(self.func_user)

    def func_user(self):
        self.Dialog.hide()
        self.open_USER()

    def func_admin(self):
        self.Dialog.hide()
        self.open_admin()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
